-- Copied from Excel file: http://faostat.fao.org/site/371/DesktopDefault.aspx?PageID=371
-- Excel Header: Faostat area code', 'ISO2', 'Area name', 'Area long name'
CREATE TABLE countries (
	country_code  integer CONSTRAINT firstkey PRIMARY KEY,
	iso_code      char(2) NOT NULL,
	name          varchar(50) NOT NULL,
	long_name     varchar(60) NOT NULL,
	type          int NOT NULL DEFAULT 1
);

INSERT INTO countries VALUES
(1, 'AM', 'Armenia', 'the Republic of Armenia', 1),
(2, 'AF', 'Afghanistan', 'The Islamic Republic of Afghanistan', 1),
(3, 'AL', 'Albania', 'the Republic of Albania', 1),
(4, 'DZ', 'Algeria', 'the Peoples Democratic Republic of Algeria', 1),
(5, 'AS', 'American Samoa', 'American Samoa', 1),
(6, 'AD', 'Andorra', 'the Principality of Andorra', 1),
(7, 'AO', 'Angola', 'the Republic of Angola', 1),
(8, 'AG', 'Antigua and Barbuda', 'Antigua and Barbuda', 1),
(9, 'AR', 'Argentina', 'the Argentine Republic', 1),
(10, 'AU', 'Australia', 'Australia', 1),
(11, 'AT', 'Austria', 'the Republic of Austria', 1),
(12, 'BS', 'Bahamas', 'the Commonwealth of the Bahamas', 1),
(13, 'BH', 'Bahrain', 'the Kingdom of Bahrain', 1),
(14, 'BB', 'Barbados', 'Barbados', 1),
(15, '..', 'Belgium-Luxembourg', 'Belgium-Luxembourg', 1),
(16, 'BD', 'Bangladesh', 'the Peoples Republic of Bangladesh', 1),
(17, 'BM', 'Bermuda', 'Bermuda', 1),
(18, 'BT', 'Bhutan', 'the Kingdom of Bhutan', 1),
(19, 'BO', 'Bolivia', 'the Plurinational State of Bolivia', 1),
--(19, 'BO', 'Bolivia (Plurinational State of)', 'the Plurinational State of Bolivia', 1),
(20, 'BW', 'Botswana', 'the Republic of Botswana', 1),
(21, 'BR', 'Brazil', 'the Federative Republic of Brazil', 1),
(22, 'AW', 'Aruba', 'Aruba', 1),
(23, 'BZ', 'Belize', 'Belize', 1),
(24, 'IO', 'British Indian Ocean Territory', 'British Indian Ocean Territory', 1),
(25, 'SB', 'Solomon Islands', 'Solomon Islands', 1),
(26, 'BN', 'Brunei Darussalam', 'Brunei Darussalam', 1),
(27, 'BG', 'Bulgaria', 'the Republic of Bulgaria', 1),
(28, 'MM', 'Myanmar', 'the Republic of the Union of Myanmar', 1),
(29, 'BI', 'Burundi', 'the Republic of Burundi', 1),
(30, 'AQ', 'Antarctica', 'Antarctica', 1),
(32, 'CM', 'Cameroon', 'the Republic of Cameroon', 1),
(33, 'CA', 'Canada', 'Canada', 1),
(35, 'CV', 'Cabo Verde', 'Republic of Cabo Verde', 1),
(36, 'KY', 'Cayman Islands', 'Cayman Islands', 1),
(37, 'CF', 'Central African Republic', 'the Central African Republic', 1),
(38, 'LK', 'Sri Lanka', 'the Democratic Socialist Republic of Sri Lanka', 1),
(39, 'TD', 'Chad', 'the Republic of Chad', 1),
(40, 'CL', 'Chile', 'the Republic of Chile', 1),
(41, 'CN', 'China, mainland', 'the Peoples Republic of China', 1),
(42, 'CX', 'Christmas Island', 'Christmas Island', 1),
(43, 'CC', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', 1),
(44, 'CO', 'Colombia', 'the Republic of Colombia', 1),
(45, 'KM', 'Comoros', 'the Union of the Comoros', 1),
(46, 'CG', 'Congo', 'the Republic of the Congo', 1),
(47, 'CK', 'Cook Islands', 'the Cook Islands', 1),
(48, 'CR', 'Costa Rica', 'the Republic of Costa Rica', 1),
(49, 'CU', 'Cuba', 'the Republic of Cuba', 1),
(50, 'CY', 'Cyprus', 'the Republic of Cyprus', 1),
(51, '..', 'Czechoslovakia', 'Czechoslovakia', 1),
(52, 'AZ', 'Azerbaijan', 'the Republic of Azerbaijan', 1),
(53, 'BJ', 'Benin', 'the Republic of Benin', 1),
(54, 'DK', 'Denmark', 'the Kingdom of Denmark', 1),
(55, 'DM', 'Dominica', 'the Commonwealth of Dominica', 1),
(56, 'DO', 'Dominican Republic', 'the Dominican Republic', 1),
(57, 'BY', 'Belarus', 'the Republic of Belarus', 1),
(58, 'EC', 'Ecuador', 'the Republic of Ecuador', 1),
(59, 'EG', 'Egypt', 'the Arab Republic of Egypt', 1),
(60, 'SV', 'El Salvador', 'the Republic of El Salvador', 1),
(61, 'GQ', 'Equatorial Guinea', 'the Republic of Equatorial Guinea', 1),
(62, '..', 'Ethiopia PDR', 'Ethiopia PDR', 1),
(63, 'EE', 'Estonia', 'the Republic of Estonia', 1),
(64, 'FO', 'Faroe Islands', 'Faroe Islands', 1),
(65, 'FK', 'Falkland Islands', 'the Falkland Islands (Malvinas)', 1),
--(65, 'FK', 'Falkland Islands (Malvinas)', 'the Falkland Islands (Malvinas)', 1),
(66, 'FJ', 'Fiji', 'the Republic of Fiji', 1),
(67, 'FI', 'Finland', 'the Republic of Finland', 1),
(68, 'FR', 'France', 'the French Republic', 1),
(69, 'GF', 'French Guiana', 'French Guiana', 1),
(70, 'PF', 'French Polynesia', 'French Polynesia', 1),
(71, 'TF', 'French Southern and Antarctic Territories', 'French Southern and Antarctic Territories', 1),
(72, 'DJ', 'Djibouti', 'the Republic of Djibouti', 1),
(73, 'GE', 'Georgia', 'Georgia', 1),
(74, 'GA', 'Gabon', 'the Gabonese Republic', 1),
(75, 'GM', 'Gambia', 'the Republic of the Gambia', 1),
(79, 'DE', 'Germany', 'the Federal Republic of Germany', 1),
(80, 'BA', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 1),
(81, 'GH', 'Ghana', 'the Republic of Ghana', 1),
(82, 'GI', 'Gibraltar', 'Gibraltar', 1),
(83, 'KI', 'Kiribati', 'the Republic of Kiribati', 1),
(84, 'GR', 'Greece', 'the Hellenic Republic', 1),
(85, 'GL', 'Greenland', 'Greenland', 1),
(86, 'GD', 'Grenada', 'Grenada', 1),
(87, 'GP', 'Guadeloupe', 'Guadeloupe', 1),
(88, 'GU', 'Guam', 'Guam', 1),
(89, 'GT', 'Guatemala', 'the Republic of Guatemala', 1),
(90, 'GN', 'Guinea', 'the Republic of Guinea', 1),
(91, 'GY', 'Guyana', 'the Republic of Guyana', 1),
(93, 'HT', 'Haiti', 'the Republic of Haiti', 1),
(94, 'VA', 'Holy See', 'Holy See', 1),
(95, 'HN', 'Honduras', 'the Republic of Honduras', 1),
(96, 'HK', 'China, Hong Kong SAR', 'China, Hong Kong Special Administrative Region', 1),
(97, 'HU', 'Hungary', 'Hungary', 1),
(98, 'HR', 'Croatia', 'the Republic of Croatia', 1),
(99, 'IS', 'Iceland', 'the Republic of Iceland', 1),
(100, 'IN', 'India', 'the Republic of India', 1),
(101, 'ID', 'Indonesia', 'the Republic of Indonesia', 1),
(102, 'IR', 'Iran', 'the Islamic Republic of Iran', 1),
--(102, 'IR', 'Iran (Islamic Republic of)', 'the Islamic Republic of Iran', 1),
(103, 'IQ', 'Iraq', 'the Republic of Iraq', 1),
(104, 'IE', 'Ireland', 'Ireland', 1),
(105, 'IL', 'Israel', 'the State of Israel', 1),
(106, 'IT', 'Italy', 'the Republic of Italy', 1),
(107, 'CI', 'Côte d Ivoire', 'the Republic of Côte d Ivoire', 1),
(108, 'KZ', 'Kazakhstan', 'the Republic of Kazakhstan', 1),
(109, 'JM', 'Jamaica', 'Jamaica', 1),
(110, 'JP', 'Japan', 'Japan', 1),
(112, 'JO', 'Jordan', 'the Hashemite Kingdom of Jordan', 1),
(113, 'KG', 'Kyrgyzstan', 'the Kyrgyz Republic', 1),
(114, 'KE', 'Kenya', 'the Republic of Kenya', 1),
(115, 'KH', 'Cambodia', 'the Kingdom of Cambodia', 1),
(116, 'KP', 'Democratic Peoples Republic of Korea', 'the Democratic Peoples Republic of Korea', 1),
(117, 'KR', 'Republic of Korea', 'the Republic of Korea', 1),
(118, 'KW', 'Kuwait', 'the State of Kuwait', 1),
(119, 'LV', 'Latvia', 'the Republic of Latvia', 1),
(120, 'LA', 'Lao Peoples Democratic Republic', 'the Lao Peoples Democratic Republic', 1),
(121, 'LB', 'Lebanon', 'the Lebanese Republic', 1),
(122, 'LS', 'Lesotho', 'the Kingdom of Lesotho', 1),
(123, 'LR', 'Liberia', 'the Republic of Liberia', 1),
(124, 'LY', 'Libya', 'Libya', 1),
(125, 'LI', 'Liechtenstein', 'the Principality of Liechtenstein', 1),
(126, 'LT', 'Lithuania', 'the Republic of Lithuania', 1),
(127, 'MH', 'Marshall Islands', 'the Republic of the Marshall Islands', 1),
(128, 'MO', 'China, Macao SAR', 'China, Macao Special Administrative Region', 1),
(129, 'MG', 'Madagascar', 'the Republic of Madagascar', 1),
(130, 'MW', 'Malawi', 'the Republic of Malawi', 1),
(131, 'MY', 'Malaysia', 'Malaysia', 1),
(132, 'MV', 'Maldives', 'the Republic of Maldives', 1),
(133, 'ML', 'Mali', 'the Republic of Mali', 1),
(134, 'MT', 'Malta', 'the Republic of Malta', 1),
(135, 'MQ', 'Martinique', 'Martinique', 1),
(136, 'MR', 'Mauritania', 'the Islamic Republic of Mauritania', 1),
(137, 'MU', 'Mauritius', 'the Republic of Mauritius', 1),
(138, 'MX', 'Mexico', 'the United Mexican States', 1),
(140, 'MC', 'Monaco', 'the Principality of Monaco', 1),
(141, 'MN', 'Mongolia', 'Mongolia', 1),
(142, 'MS', 'Montserrat', 'Montserrat', 1),
(143, 'MA', 'Morocco', 'the Kingdom of Morocco', 1),
(144, 'MZ', 'Mozambique', 'the Republic of Mozambique', 1),
(145, 'FM', 'Micronesia', 'the Federated States of Micronesia', 1),
--(145, 'FM', 'Micronesia (Federated States of)', 'the Federated States of Micronesia', 1),
(146, 'MD', 'Republic of Moldova', 'the Republic of Moldova', 1),
(147, 'NA', 'Namibia', 'the Republic of Namibia', 1),
(148, 'NR', 'Nauru', 'the Republic of Nauru', 1),
(149, 'NP', 'Nepal', 'the Federal Democratic Republic of Nepal', 1),
(150, 'NL', 'Netherlands', 'the Kingdom of the Netherlands', 1),
(151, 'AN', 'Netherlands Antilles', 'Netherlands Antilles', 1),
(153, 'NC', 'New Caledonia', 'New Caledonia', 1),
(154, 'MK', 'The former Yugoslav Republic of Macedonia', 'The former Yugoslav Republic of Macedonia', 1),
(155, 'VU', 'Vanuatu', 'the Republic of Vanuatu', 1),
(156, 'NZ', 'New Zealand', 'New Zealand', 1),
(157, 'NI', 'Nicaragua', 'the Republic of Nicaragua', 1),
(158, 'NE', 'Niger', 'the Republic of the Niger', 1),
(159, 'NG', 'Nigeria', 'the Federal Republic of Nigeria', 1),
(160, 'NU', 'Niue', 'Niue', 1),
(161, 'NF', 'Norfolk Island', 'Territory of Norfolk Island', 1),
(162, 'NO', 'Norway', 'the Kingdom of Norway', 1),
(163, 'MP', 'Northern Mariana Islands', 'The Commonwealth of the Northern Mariana Islands', 1),
(164, '..', 'Pacific Islands Trust Territory', 'Pacific Islands Trust Territory', 1),
(165, 'PK', 'Pakistan', 'the Islamic Republic of Pakistan', 1),
(166, 'PA', 'Panama', 'the Republic of Panama', 1),
(167, 'CZ', 'Czech Republic', 'the Czech Republic', 1),
(168, 'PG', 'Papua New Guinea', 'Independent State of Papua New Guinea', 1),
(169, 'PY', 'Paraguay', 'the Republic of Paraguay', 1),
(170, 'PE', 'Peru', 'the Republic of Peru', 1),
(171, 'PH', 'Philippines', 'the Republic of the Philippines', 1),
(172, 'PN', 'Pitcairn Islands', 'Pitcairn Islands', 1),
(173, 'PL', 'Poland', 'the Republic of Poland', 1),
(174, 'PT', 'Portugal', 'the Portuguese Republic', 1),
(175, 'GW', 'Guinea-Bissau', 'the Republic of Guinea-Bissau', 1),
(176, 'TL', 'Timor-Leste', 'the Democratic Republic of Timor-Leste', 1),
(177, 'PR', 'Puerto Rico', 'the Commonwealth of Puerto Rico', 1),
(178, 'ER', 'Eritrea', 'the State of Eritrea', 1),
(179, 'QA', 'Qatar', 'the State of Qatar', 1),
(180, 'PW', 'Palau', 'the Republic of Palau', 1),
(181, 'ZW', 'Zimbabwe', 'the Republic of Zimbabwe', 1),
(182, 'RE', 'Réunion', 'Réunion', 1),
(183, 'RO', 'Romania', 'Romania', 1),
(184, 'RW', 'Rwanda', 'the Republic of Rwanda', 1),
(185, 'RU', 'Russian Federation', 'the Russian Federation', 1),
(186, 'CS', 'Serbia and Montenegro', 'Serbia and Montenegro', 1),
(187, 'SH', 'Saint Helena', 'Saint Helena, Ascension and Tristan da Cunha', 1),
--(187, 'SH', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha', 1),
(188, 'KN', 'Saint Kitts and Nevis', 'Saint Kitts and Nevis', 1),
(189, 'LC', 'Saint Lucia', 'Saint Lucia', 1),
(190, 'PM', 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', 1),
(191, 'VC', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 1),
(192, 'SM', 'San Marino', 'the Republic of San Marino', 1),
(193, 'ST', 'Sao Tome and Principe', 'the Democratic Republic of Sao Tome and Principe', 1),
(194, 'SA', 'Saudi Arabia', 'the Kingdom of Saudi Arabia', 1),
(195, 'SN', 'Senegal', 'the Republic of Senegal', 1),
(196, 'SC', 'Seychelles', 'the Republic of Seychelles', 1),
(197, 'SL', 'Sierra Leone', 'the Republic of Sierra Leone', 1),
(198, 'SI', 'Slovenia', 'the Republic of Slovenia', 1),
(199, 'SK', 'Slovakia', 'the Slovak Republic', 1),
(200, 'SG', 'Singapore', 'the Republic of Singapore', 1),
(201, 'SO', 'Somalia', 'the Federal Republic of Somalia', 1),
(202, 'ZA', 'South Africa', 'the Republic of South Africa', 1),
(203, 'ES', 'Spain', 'the Kingdom of Spain', 1),
(205, 'EH', 'Western Sahara', 'Western Sahara', 1),
(206, 'SD', 'Sudan (former)', 'the Republic of the Sudan (former)', 1),
(207, 'SR', 'Suriname', 'the Republic of Suriname', 1),
(208, 'TJ', 'Tajikistan', 'the Republic of Tajikistan', 1),
(209, 'SZ', 'Swaziland', 'the Kingdom of Swaziland', 1),
(210, 'SE', 'Sweden', 'the Kingdom of Sweden', 1),
(211, 'CH', 'Switzerland', 'the Swiss Confederation', 1),
(212, 'SY', 'Syrian Arab Republic', 'the Syrian Arab Republic', 1),
(213, 'TM', 'Turkmenistan', 'Turkmenistan', 1),
(214, 'TW', 'Taiwan', 'Taiwan Province of China', 1),
--(214, 'TW', 'China, Taiwan Province of', 'Taiwan Province of China', 1),
(215, 'TZ', 'United Republic of Tanzania', 'the United Republic of Tanzania', 1),
(216, 'TH', 'Thailand', 'the Kingdom of Thailand', 1),
(217, 'TG', 'Togo', 'the Togolese Republic', 1),
(218, 'TK', 'Tokelau', 'Tokelau', 1),
(219, 'TO', 'Tonga', 'the Kingdom of Tonga', 1),
(220, 'TT', 'Trinidad and Tobago', 'the Republic of Trinidad and Tobago', 1),
(221, 'OM', 'Oman', 'the Sultanate of Oman', 1),
(222, 'TN', 'Tunisia', 'the Republic of Tunisia', 1),
(223, 'TR', 'Turkey', 'the Republic of Turkey', 1),
(224, 'TC', 'Turks and Caicos Islands', 'Turks and Caicos Islands', 1),
(225, 'AE', 'United Arab Emirates', 'the United Arab Emirates', 1),
(226, 'UG', 'Uganda', 'the Republic of Uganda', 1),
(227, 'TV', 'Tuvalu', 'Tuvalu', 1),
(228, '..', 'USSR', 'USSR', 1),
(229, 'GB', 'United Kingdom', 'the United Kingdom of Great Britain and Northern Ireland', 1),
(230, 'UA', 'Ukraine', 'Ukraine', 1),
(231, 'US', 'United States of America', 'the United States of America', 1),
(233, 'BF', 'Burkina Faso', 'Burkina Faso', 1),
(234, 'UY', 'Uruguay', 'the Eastern Republic of Uruguay', 1),
(235, 'UZ', 'Uzbekistan', 'the Republic of Uzbekistan', 1),
(236, 'VE', 'Venezuela', 'the Bolivarian Republic of Venezuela', 1),
--(236, 'VE', 'Venezuela (Bolivarian Republic of)', 'the Bolivarian Republic of Venezuela', 1),
(237, 'VN', 'Viet Nam', 'the Socialist Republic of Viet Nam', 1),
(238, 'ET', 'Ethiopia', 'the Federal Democratic Republic of Ethiopia', 1),
(239, 'VG', 'British Virgin Islands', 'the British Virgin Islands', 1),
(240, 'VI', 'United States Virgin Islands', 'the United States Virgin Islands', 1),
(242, 'WK', 'Wake Island', 'Wake Island', 1),
(243, 'WF', 'Wallis and Futuna Islands', 'Wallis and Futuna Islands', 1),
(244, 'WS', 'Samoa', 'the Independent State of Samoa', 1),
(247, '..', 'Yemen Dem', 'Yemen, Democratic', 1),
(248, '..', 'Yugoslav SFR', 'Yugoslavia SFR', 1),
(249, 'YE', 'Yemen', 'the Republic of Yemen', 1),
(250, 'CD', 'Democratic Republic of the Congo', 'the Democratic Republic of the Congo', 1),
(251, 'ZM', 'Zambia', 'the Republic of Zambia', 1),
(252, '', 'Unspecified', 'Unspecified', 1),
(254, '', 'Others (adjustment)', 'Others (adjustment)', 1),
(255, 'BE', 'Belgium', 'the Kingdom of Belgium', 1),
(256, 'LU', 'Luxembourg', 'the Grand Duchy of Luxembourg', 1),
(258, 'AI', 'Anguilla', 'Anguilla', 1),
(259, '..', 'Channel Islands', 'Channel Islands', 1),
(260, 'SJ', 'Svalbard and Jan Mayen Islands', 'Svalbard and Jan Mayen Islands', 1),
(264, 'IM', 'Isle of Man', 'Isle of Man', 1),
(270, 'YT', 'Mayotte', 'Mayotte', 1),
(272, 'RS', 'Serbia', 'the Republic of Serbia', 1),
(273, 'ME', 'Montenegro', 'Montenegro', 1),
(276, 'SD', 'Sudan', 'the Republic of the Sudan', 1),
(277, 'SS', 'South Sudan', 'the Republic of South Sudan', 1),
(279, '', 'Curaçao', 'Curaçao', 1),
(280, '', 'Sint Maarten (Dutch Part)', 'Sint Maarten (Dutch Part)', 1),
(281, '', 'Saint-Martin (French Part)', 'Saint-Martin (French Part)', 1),
(299, '..', 'Occupied Palestinian Territory', 'Occupied Palestinian Territory', 1),
(351, '', 'China', 'the Peoples Republic of China', 1),
(5000, '', 'World', 'World', 2),
(5009, '', 'Total FAO', 'Total FAO', 2),
(5100, '', 'Africa', 'Africa', 2),
(5101, '', 'Eastern Africa', 'Eastern Africa', 2),
(5102, '', 'Middle Africa', 'Middle Africa', 2),
(5103, '', 'Northern Africa', 'Northern Africa', 2),
(5104, '', 'Southern Africa', 'Southern Africa', 2),
(5105, '', 'Western Africa', 'Western Africa', 2),
(5200, '', 'Americas', 'Americas', 2),
(5203, '', 'Northern America', 'Northern America', 2),
(5204, '', 'Central America', 'Central America', 2),
(5206, '', 'Caribbean', 'Caribbean', 2),
(5207, '', 'South America', 'South America', 2),
(5300, '', 'Asia', 'Asia', 2),
(5301, '', 'Central Asia', 'Central Asia', 2),
(5302, '', 'Eastern Asia', 'Eastern Asia', 2),
(5303, '', 'Southern Asia', 'Southern Asia', 2),
(5304, '', 'South-Eastern Asia', 'South-Eastern Asia', 2),
(5305, '', 'Western Asia', 'Western Asia', 2),
(5400, '', 'Europe', 'Europe', 2),
(5401, '', 'Eastern Europe', 'Eastern Europe', 2),
(5402, '', 'Northern Europe', 'Northern Europe', 2),
(5403, '', 'Southern Europe', 'Southern Europe', 2),
(5404, '', 'Western Europe', 'Western Europe', 2),
(5500, '', 'Oceania', 'Oceania', 2),
(5501, '', 'Australia & New Zealand', 'Australia and New Zealand', 2),
(5502, '', 'Melanesia', 'Melanesia', 2),
(5503, '', 'Micronesia', 'Micronesia', 2),
(5504, '', 'Polynesia', 'Polynesia', 2),
(5600, '', 'Antarctic Region', 'Antarctic Region', 2),
(5706, '', 'European Union', 'European Union', 2),
(5801, '', 'Least Developed Countries', 'Least Developed Countries', 2),
(5802, '', 'Land Locked Developing Countries', 'LandLocked developing countries', 2),
(5803, '', 'Small Island Developing States', 'Small Island Developing States', 2),
(5815, '', 'Low Income Food Deficit Countries', 'Low Income Food Deficit Countries', 2),
(5817, '', 'Net Food Importing Developing Countries', 'Net Food Importing Developing Countries', 2),
(5848, '', 'Annex I countries', 'Annex I countries', 2),
(5849, '', 'Non-Annex I countries', 'Non-Annex I countries', 2);