# 
# 1. Download data from faostat
# 2. Load into postgres
# 3. Transform
# 4. Export to S3, for easy importing on-demand

name: faostat-transform-to-s3

on:
  workflow_dispatch:

permissions:
  id-token: write # required for aws oidc access

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Download faostat, import into postgres and transform
      run: |
        cd etl/postgresql
        time bash -x import.sh
    - name: Export to csv archives
      run: |
        cd etl/postgresql
        bash -x export-to-s3.sh
    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::779071549559:role/aws-github-oidc-foodbrowser
        role-session-name: foodbrowser-write-to-s3-role-session
        aws-region: eu-west-1
    - name: Upload csv archives to S3
      run: |
        prefix=$(TZ=":Europe/Berlin" date +'%Y%m%d-%H%M%S')
        aws s3 cp /tmp/export s3://foodbrowser/$prefix/ --recursive

